import { useState } from 'react';
import { X, ChevronDown, ChevronRight, HelpCircle, Brain, TestTube, Bug, Shield, Zap } from 'lucide-react';
import clsx from 'clsx';

interface AboutDevPilotProps {
  onClose: () => void;
}

const QA = [
  {
    icon: <HelpCircle className="w-4 h-4" />,
    question: 'What makes DevPilot different?',
    answer: 'DevPilot connects repository understanding, planning, implementation, testing, debugging, and engineering evaluation into one workflow.',
  },
  {
    icon: <Brain className="w-4 h-4" />,
    question: 'Why not just use an AI coding assistant?',
    answer: 'Coding assistants are excellent at generating code. DevPilot focuses on the complete engineering loop, including verification and recovery.',
  },
  {
    icon: <Brain className="w-4 h-4" />,
    question: 'How does DevPilot understand a repository?',
    answer: 'The RepositoryAnalyzer walks the filesystem, detects languages by extension, identifies frameworks via dependency markers, and maps the project structure — all without AI.',
  },
  {
    icon: <TestTube className="w-4 h-4" />,
    question: 'How does DevPilot test changes?',
    answer: 'The TestAgent auto-detects the test framework from project markers and runs tests via subprocess, returning actual command output.',
  },
  {
    icon: <Bug className="w-4 h-4" />,
    question: 'How does debugging work?',
    answer: 'The DebuggingAgent sends test output and source code to an AI model, which identifies root causes and suggests fixes.',
  },
  {
    icon: <Shield className="w-4 h-4" />,
    question: 'How is Engineering Health calculated?',
    answer: 'Scores are generated by the ReportAgent using AI analysis. Each category is assessed independently. DevPilot Engineering Health is an AI-assisted project assessment.',
  },
  {
    icon: <Zap className="w-4 h-4" />,
    question: 'What happens when AI fails?',
    answer: 'The application falls back to Demo Mode. Errors are displayed with retry options. No blank screens.',
  },
];

export default function AboutDevPilot({ onClose }: AboutDevPilotProps) {
  const [expanded, setExpanded] = useState<number | null>(null);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-surface-950/80 backdrop-blur-sm">
      <div className="rounded-xl border border-surface-800/50 bg-surface-950 w-full max-w-lg max-h-[80vh] flex flex-col overflow-hidden">
        <div className="flex items-center justify-between px-5 py-4 border-b border-surface-800/50">
          <h2 className="text-sm font-semibold text-white">About DevPilot</h2>
          <button onClick={onClose} className="text-surface-400 hover:text-white transition-colors">
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="overflow-y-auto divide-y divide-surface-800/50">
          {QA.map((item, i) => (
            <button
              key={i}
              onClick={() => setExpanded(expanded === i ? null : i)}
              className="w-full text-left px-5 py-3.5 flex items-start gap-3 hover:bg-surface-800/20 transition-colors"
            >
              <span className="text-surface-500 mt-0.5 flex-shrink-0">{item.icon}</span>
              <span className="flex-1 min-w-0">
                <span className={clsx('text-sm font-medium', expanded === i ? 'text-brand-400' : 'text-surface-300')}>
                  {item.question}
                </span>
                {expanded === i && (
                  <p className="mt-1.5 text-xs text-surface-400 leading-relaxed">{item.answer}</p>
                )}
              </span>
              <span className="text-surface-500 mt-0.5 flex-shrink-0">
                {expanded === i ? <ChevronDown className="w-3.5 h-3.5" /> : <ChevronRight className="w-3.5 h-3.5" />}
              </span>
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}
