# Auto-generated demo responses for mock AI mode
# Each response is distinctly different per personality x action combination.
from typing import Any


DEMO_RESPONSES: dict[str, dict[str, str]] = {
    "mentor": {
        "explain": "Let me walk you through this code step by step — understanding the 'why' matters more than memorizing the fix.\n\n**What this function does:**\nIt takes a user ID, queries the database asynchronously, and returns the user's name.\n\n**Key concept — async/await:**\nThe `await` keyword means this function pauses execution until `db.find()` completes. Think of it like placing an order at a restaurant — you don't stand at the counter; you wait at your table.\n\n**Now, here's something important to think about:**\nWhat happens if `db.find(id)` doesn't find anyone? The result would be `undefined`, and then `user.name` would crash with a TypeError — like trying to read the name tag of someone who isn't there.\n\nCan you think of a way to handle that gracefully before we look at solutions?",
        "review": "Let's review this together — I'll point out what's working and where we can learn.\n\n**What's good:**\n- Clean TypeScript types on the parameter\n- Proper async/await usage\n\n**Something to think about:**\nHere's a question for you: what does `db.find()` return when no user matches the ID? If you said `undefined`, you're right! And what happens when you try `.name` on `undefined`?\n\nThis is a great example of why defensive coding matters. In production, users get deleted, IDs get mistyped, databases have temporary issues — all of which would cause this function to crash.\n\n**How would you approach fixing this?** Would you return `null`, throw an error, or use a different pattern?",
        "debug": "Let's think through this like a debugging exercise — what could go wrong?\n\n**Step 1:** Look at the return type of `db.find()`. Is it guaranteed to be a `User` object, or could it be `undefined`?\n\n**Step 2:** If the user doesn't exist in the database (maybe they were deleted, or the ID is wrong), what value does `db.find()` return?\n\n**Step 3:** When you access `.name` on `undefined`, what happens? (Hint: it's a TypeError)\n\n**Before I show you the fix:** What do you think would be a good strategy? Should we:\n- Throw a descriptive error?\n- Return `null` and change the function signature?\n- Return a default value?\n\nThere's no single right answer — it depends on how callers use this function. What would you choose?",
        "improve": "Let's think about improving this code together — design decisions matter more than syntax.\n\n**Current design:**\nThe function assumes the user always exists and directly accesses `user.name`.\n\n**A question to consider:**\nWhat's the contract of this function? If someone calls `getUser(id)`, what should they be able to expect?\n- Always get a string? (Then we need a fallback)\n- Get `string | null`? (Then callers must handle null)\n- Get an error on missing user? (Then we throw explicitly)\n\n**There's no single 'right' answer** — it depends on your architecture. For a service layer, throwing is often preferred because it makes failures explicit. For a UI component, returning null might be more convenient.\n\nWhat approach makes the most sense in your application's context?",
        "ask": "Great question! Let me explain the concepts at play here.\n\n**Async/Await:**\nThis function uses `await` to handle the asynchronous database call. Think of it as a promise: \"I'll give you the result when it's ready, but don't block other work while waiting.\"\n\n**Type Safety:**\nTypeScript helps catch errors at compile time — but only if we use it correctly. The type system assumes `db.find()` returns a `User`, but at runtime it could return `undefined`.\n\n**The gap between compile-time and runtime:**\nThis is a classic example of where TypeScript's type system and JavaScript's runtime behavior diverge. Types tell us what *should* happen; runtime tells us what *actually* happens.\n\nWould you like me to dive deeper into any of these concepts?"
    },
    "senior_engineer": {
        "explain": "Fetches user by ID, returns name.\n\n**Runtime risk:** `db.find()` can return `undefined`. `user.name` on undefined throws TypeError.\n\n**Fix:** Guard before access.\n```typescript\nconst user = await db.find(id);\nif (!user) throw new UserNotFoundError(id);\nreturn user.name;\n```\n\n**Trade-off:** Throwing is explicit. Returning `string | null` changes the contract. Pick based on your error-handling strategy.",
        "review": "**Review findings:**\n\n**HIGH — Unhandled undefined access**\n`user.name` accessed without validating `db.find()` result. TypeError at runtime when user not found.\n\n```typescript\nconst user = await db.find(id);\nif (!user) throw new UserNotFoundError(id);\nreturn user.name;\n```\n\n**MEDIUM — No error boundary**\nDatabase connection failures propagate unhandled. Consider wrapping in try/catch or using a global error handler.\n\n**LOW — Missing return type**\nExplicit `Promise<string>` improves API contracts.\n\n**Trade-off:** Throwing vs returning null. For service layers, throwing is usually correct — callers should handle errors, not check for null everywhere.",
        "debug": "**Root cause:** `db.find()` returns `User | undefined`. No null check before property access.\n\n**Fix:**\n```typescript\nconst user = await db.find(id);\nif (!user) throw new Error(`User ${id} not found`);\nreturn user.name;\n```\n\n**Prevention:** Enable `strictNullChecks` in tsconfig.json. This catches missing null checks at compile time.\n\n**Note:** If this is a critical path, also add input validation on `id` and consider retry logic for transient DB failures.",
        "improve": "**Current:** Direct property access on potentially undefined result.\n\n**Problem:** Runtime crash when user not found.\n\n**Recommended:**\n```typescript\nasync function getUser(id: string): Promise<string> {\n    if (!id) throw new ValueError('ID required');\n    const user = await db.find(id);\n    if (!user) throw new UserNotFoundError(id);\n    return user.name;\n}\n```\n\n**Trade-offs:** Explicit error handling (throw) vs nullable return type. For a service layer, throwing is preferred — it makes failure modes explicit and forces callers to handle errors.",
        "ask": "Based on the code:\n\nThe function queries a database asynchronously and returns a user's name. Key concern: `db.find()` can return `undefined` — accessing `.name` on that throws a TypeError.\n\n**Production recommendation:** Always validate the result before property access. Enable TypeScript `strictNullChecks` to catch these at compile time.\n\nFor this specific case, throwing on missing user is the right call — it makes the failure explicit."
    },
    "strict_reviewer": {
        "explain": "**Code Analysis — Severity-Classified Findings:**\n\n**HIGH — Unhandled undefined access**\nLine: `return user.name;`\n`db.find()` returns `User | undefined`. Direct property access without null validation causes runtime TypeError.\n\n**MEDIUM — No error handling**\nNo try/catch or error boundary. Database failures propagate unhandled to caller.\n\n**LOW — Missing return type annotation**\nWhile TypeScript infers `Promise<string>`, explicit annotation improves API contracts and readability.\n\n**INFO — Consider input validation**\nNo validation on `id` parameter. Empty string or malformed input could cause unexpected behavior.\n\n**Required fixes:**\n1. Add null guard: `if (!user) throw new Error(...)`\n2. Consider try/catch for DB errors\n3. Add explicit return type: `Promise<string>`\n4. Validate `id` parameter",
        "review": "**CRITICAL — Potential runtime exception**\n\nFile: Current code\nLine: `return user.name;`\n\n`db.find()` may return `undefined`. Direct property access without validation will throw TypeError when user not found.\n\n**Required fix:**\n```typescript\nconst user = await db.find(id);\nif (!user) throw new UserNotFoundError(id);\nreturn user.name;\n```\n\n**Additional defects:**\n- **MEDIUM:** No error boundary for database connection failures\n- **LOW:** Missing explicit return type annotation `Promise<string>`\n- **INFO:** No input validation on `id` parameter\n\n**Severity justification:** HIGH because this is a runtime crash on a common code path (user deletion, invalid IDs). Not CRITICAL because it's easily fixable and doesn't cause data corruption.",
        "debug": "**CRITICAL — Runtime exception identified**\n\n**Defect:** `user.name` accessed on potentially undefined value\n**Root cause:** `db.find()` returns `User | undefined`, no null check exists\n**Affected paths:** Any call with non-existent user ID\n**Fix:** Add explicit null guard before property access\n**Prevention:** Enable TypeScript `strictNullChecks` compiler option\n\n**Confidence:** 95%\n**Severity:** HIGH — Common runtime error, easily triggered by deleted users or mistyped IDs\n\n**Edge cases to verify:**\n- Empty string ID\n- Valid ID but deleted user\n- Database connection timeout\n- Concurrent deletion during fetch",
        "improve": "**Code quality assessment:**\n\n**CRITICAL:** No null check on `db.find()` result before property access\n**HIGH:** No error handling for database failures\n**MEDIUM:** Missing explicit return type annotation\n**LOW:** No input validation on `id` parameter\n\n**Improved version:**\n```typescript\nasync function getUser(id: string): Promise<string> {\n    if (!id) throw new ValueError('ID required');\n    const user = await db.find(id);\n    if (!user) throw new UserNotFoundError(id);\n    return user.name;\n}\n```\n\n**Additional recommendations:**\n- Add try/catch for database errors\n- Consider retry logic for transient failures\n- Log the error with context for debugging\n- Add unit tests for all failure modes",
        "ask": "**Technical assessment:**\n\nThe function has a **HIGH severity** safety gap: `db.find()` return type must be validated before property access.\n\n**Why this matters:**\nThis is a common source of runtime errors in TypeScript projects. The type system says it's safe; runtime says otherwise.\n\n**Recommendation:**\n1. Enable `strictNullChecks` in tsconfig.json\n2. Add null guard: `if (!user) throw new Error(...)`\n3. Consider input validation on `id`\n4. Add error boundary for database failures\n\n**Severity:** HIGH — Easily triggered, no data corruption, straightforward fix."
    },
    "interview_coach": {
        "explain": "Before I explain, let me ask you some questions to make sure we're building understanding:\n\n1. **What does `db.find(id)` return** if no user with that ID exists in the database?\n2. **What happens when you access `.name`** on that return value?\n3. **Can you think of a scenario** where this code works fine in testing but fails in production?\n\n(Think about it — testing often uses mock data where users always exist, but production has real deletions and mistyped IDs.)\n\nTake a moment to reason through each one. Understanding the 'why' is more valuable than just knowing the fix.",
        "review": "Let's review this together. I'll ask questions — try to answer each one before I share my assessment.\n\n1. **Correctness:** What does `db.find()` return when no user exists with that ID?\n2. **What happens next:** If `db.find()` returns `undefined`, what does `user.name` do?\n3. **Edge cases:** Besides 'user not found', what other failure modes should we consider?\n   - What if the database is down?\n   - What if `id` is an empty string?\n   - What if there's a network timeout?\n4. **How would you test this?** What test cases would you write?\n\nTry to think through each one before I share my findings.",
        "debug": "Good debugging exercise. Let me guide you through the thinking process.\n\n**Step 1:** What type does `db.find()` return? Is it `User` or `User | undefined`?\n\n**Step 2:** If the user doesn't exist in the database, what value does `db.find()` return?\n\n**Step 3:** What happens when you try to access `.name` on `undefined`?\n\n**Step 4:** How would you fix this?\n- Should we return `null` and change the function signature?\n- Should we throw an error with a descriptive message?\n- Should we return a default value?\n\n**Bonus question:** How would you write a test for this? What test cases would cover the failure modes?\n\nShare your thoughts before I reveal the recommended approach.",
        "improve": "Let's approach this as a design discussion.\n\n**Questions to consider:**\n1. What is the contract of this function? What should callers be able to expect?\n2. If the user isn't found, what's the most appropriate response for your application?\n   - Throw an error? (Explicit, forces callers to handle)\n   - Return null? (Flexible, but easy to forget null checks)\n   - Return a default? (Convenient, but hides errors)\n3. Should the function handle errors internally or let them propagate?\n4. How would you test this function? What edge cases matter?\n\n**There's no single 'right' answer** — it depends on your architecture and error-handling strategy.\n\nWhat approach would you take, and why? How does it fit with the rest of your codebase's patterns?",
        "ask": "Before I answer, let me help you think through this.\n\n1. **What specifically** about this code are you unsure about?\n2. **Have you considered** what happens when `db.find()` doesn't find a match?\n3. **How would you test this function** to make sure it handles all cases?\n\nTry to formulate your own answer first, then we can compare approaches.\n\n**Hint:** The key insight is the gap between what TypeScript *says* will happen and what *actually* happens at runtime."
    }
}
